// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: replay.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.sentry.replay.android.proto;

@kotlin.jvm.JvmName("-initializecoordinateF")
public inline fun coordinateF(block: io.sentry.replay.android.proto.CoordinateFKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF =
  io.sentry.replay.android.proto.CoordinateFKt.Dsl._create(io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `io.sentry.replay.android.proto.CoordinateF`
 */
public object CoordinateFKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF = _builder.build()

    /**
     * `float x = 1;`
     */
    public var x: kotlin.Float
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * `float x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `float y = 2;`
     */
    public var y: kotlin.Float
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * `float y = 2;`
     */
    public fun clearY() {
      _builder.clearY()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF.copy(block: io.sentry.replay.android.proto.CoordinateFKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF =
  io.sentry.replay.android.proto.CoordinateFKt.Dsl._create(this.toBuilder()).apply { block() }._build()

