// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: replay.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

package io.sentry.replay.android.proto;

@kotlin.jvm.JvmName("-initializedrawRoundRectCommand")
public inline fun drawRoundRectCommand(block: io.sentry.replay.android.proto.DrawRoundRectCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand =
    io.sentry.replay.android.proto.DrawRoundRectCommandKt.Dsl._create(io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand.newBuilder())
        .apply { block() }._build()

/**
 * Protobuf type `io.sentry.replay.android.proto.DrawRoundRectCommand`
 */
public object DrawRoundRectCommandKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand.Builder
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand.Builder): Dsl =
                Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand =
            _builder.build()

        /**
         * `.io.sentry.replay.android.proto.RectF rect = 1;`
         */
        public var rect: io.sentry.replay.android.proto.ReplayOuterClass.RectF
            @JvmName("getRect")
            get() = _builder.getRect()
            @JvmName("setRect")
            set(value) {
                _builder.setRect(value)
            }

        /**
         * `.io.sentry.replay.android.proto.RectF rect = 1;`
         */
        public fun clearRect() {
            _builder.clearRect()
        }

        /**
         * `.io.sentry.replay.android.proto.RectF rect = 1;`
         * @return Whether the rect field is set.
         */
        public fun hasRect(): kotlin.Boolean {
            return _builder.hasRect()
        }

        /**
         * `.io.sentry.replay.android.proto.CoordinateF radii = 2;`
         */
        public var radii: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF
            @JvmName("getRadii")
            get() = _builder.getRadii()
            @JvmName("setRadii")
            set(value) {
                _builder.setRadii(value)
            }

        /**
         * `.io.sentry.replay.android.proto.CoordinateF radii = 2;`
         */
        public fun clearRadii() {
            _builder.clearRadii()
        }

        /**
         * `.io.sentry.replay.android.proto.CoordinateF radii = 2;`
         * @return Whether the radii field is set.
         */
        public fun hasRadii(): kotlin.Boolean {
            return _builder.hasRadii()
        }

        /**
         * `.io.sentry.replay.android.proto.Paint paint = 3;`
         */
        public var paint: io.sentry.replay.android.proto.ReplayOuterClass.Paint
            @JvmName("getPaint")
            get() = _builder.getPaint()
            @JvmName("setPaint")
            set(value) {
                _builder.setPaint(value)
            }

        /**
         * `.io.sentry.replay.android.proto.Paint paint = 3;`
         */
        public fun clearPaint() {
            _builder.clearPaint()
        }

        /**
         * `.io.sentry.replay.android.proto.Paint paint = 3;`
         * @return Whether the paint field is set.
         */
        public fun hasPaint(): kotlin.Boolean {
            return _builder.hasPaint()
        }
    }
}

@kotlin.jvm.JvmSynthetic
public inline fun io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand.copy(block: io.sentry.replay.android.proto.DrawRoundRectCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommand =
    io.sentry.replay.android.proto.DrawRoundRectCommandKt.Dsl._create(this.toBuilder())
        .apply { block() }._build()

public val io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommandOrBuilder.rectOrNull: io.sentry.replay.android.proto.ReplayOuterClass.RectF?
    get() = if (hasRect()) getRect() else null

public val io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommandOrBuilder.radiiOrNull: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF?
    get() = if (hasRadii()) getRadii() else null

public val io.sentry.replay.android.proto.ReplayOuterClass.DrawRoundRectCommandOrBuilder.paintOrNull: io.sentry.replay.android.proto.ReplayOuterClass.Paint?
    get() = if (hasPaint()) getPaint() else null

