// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: replay.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.sentry.replay.android.proto;

@kotlin.jvm.JvmName("-initializedrawCircleCommand")
public inline fun drawCircleCommand(block: io.sentry.replay.android.proto.DrawCircleCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand =
  io.sentry.replay.android.proto.DrawCircleCommandKt.Dsl._create(io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `io.sentry.replay.android.proto.DrawCircleCommand`
 */
public object DrawCircleCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand = _builder.build()

    /**
     * `.io.sentry.replay.android.proto.CoordinateF position = 1;`
     */
    public var position: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * `.io.sentry.replay.android.proto.CoordinateF position = 1;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * `.io.sentry.replay.android.proto.CoordinateF position = 1;`
     * @return Whether the position field is set.
     */
    public fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }

    /**
     * `float radius = 2;`
     */
    public var radius: kotlin.Float
      @JvmName("getRadius")
      get() = _builder.getRadius()
      @JvmName("setRadius")
      set(value) {
        _builder.setRadius(value)
      }
    /**
     * `float radius = 2;`
     */
    public fun clearRadius() {
      _builder.clearRadius()
    }

    /**
     * `.io.sentry.replay.android.proto.Paint paint = 3;`
     */
    public var paint: io.sentry.replay.android.proto.ReplayOuterClass.Paint
      @JvmName("getPaint")
      get() = _builder.getPaint()
      @JvmName("setPaint")
      set(value) {
        _builder.setPaint(value)
      }
    /**
     * `.io.sentry.replay.android.proto.Paint paint = 3;`
     */
    public fun clearPaint() {
      _builder.clearPaint()
    }
    /**
     * `.io.sentry.replay.android.proto.Paint paint = 3;`
     * @return Whether the paint field is set.
     */
    public fun hasPaint(): kotlin.Boolean {
      return _builder.hasPaint()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand.copy(block: io.sentry.replay.android.proto.DrawCircleCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommand =
  io.sentry.replay.android.proto.DrawCircleCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommandOrBuilder.positionOrNull: io.sentry.replay.android.proto.ReplayOuterClass.CoordinateF?
  get() = if (hasPosition()) getPosition() else null

public val io.sentry.replay.android.proto.ReplayOuterClass.DrawCircleCommandOrBuilder.paintOrNull: io.sentry.replay.android.proto.ReplayOuterClass.Paint?
  get() = if (hasPaint()) getPaint() else null

