// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: replay.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.sentry.replay.android.proto;

@kotlin.jvm.JvmName("-initializerestoreToCountCommand")
public inline fun restoreToCountCommand(block: io.sentry.replay.android.proto.RestoreToCountCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand =
  io.sentry.replay.android.proto.RestoreToCountCommandKt.Dsl._create(io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `io.sentry.replay.android.proto.RestoreToCountCommand`
 */
public object RestoreToCountCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand = _builder.build()

    /**
     * `int32 count = 1;`
     */
    public var count: kotlin.Int
      @JvmName("getCount")
      get() = _builder.getCount()
      @JvmName("setCount")
      set(value) {
        _builder.setCount(value)
      }
    /**
     * `int32 count = 1;`
     */
    public fun clearCount() {
      _builder.clearCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand.copy(block: io.sentry.replay.android.proto.RestoreToCountCommandKt.Dsl.() -> kotlin.Unit): io.sentry.replay.android.proto.ReplayOuterClass.RestoreToCountCommand =
  io.sentry.replay.android.proto.RestoreToCountCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

